---
# docker tasks for setup

- name: Install docker
  tags:
    - docker

  block:

    - name: Install apt required packages
      ansible.builtin.apt:
        name: "{{ setup_docker_required_packages }}"
        state: present
        update_cache: true

    - name: Add docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Add apt docker packages
      ansible.builtin.apt:
        name: "{{ setup_docker_packages }}"
        state: present
        update_cache: true

    - name: Add original (pre-become) user to docker group
      vars:
        docker_user: >-
          {{ ansible_env.SUDO_USER
            | default(ansible_ssh_user
            | default(ansible_user
            | default(ansible_env.USER))) }}
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true
