---
# docker tasks for setup

- name: Install apt required packages
  ansible.builtin.apt:
    name: "{{ setup_docker_required_packages }}"
    state: present
    update_cache: true
  tags:
    - docker

- name: Add docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags:
    - docker

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  tags:
    - docker

- name: Add apt docker packages
  ansible.builtin.apt:
    name: "{{ setup_docker_packages }}"
    state: present
    update_cache: true
  tags:
    - docker
