---
# fish shell tasks for setup

- name: Configure Fish

  block:

    - name: Fetch fish PPA public key (armored)
      ansible.builtin.get_url:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x88421E703EDC7AF54967DED473C9FCC9E2BB48DA"
        dest: /usr/share/keyrings/fish-shell-release-4.asc
        mode: "0644"
      become: true

    - name: De-armor fish PPA key to system keyring
      ansible.builtin.command:
        argv:
          - gpg
          - --dearmor
          - --yes
          - --output
          - /usr/share/keyrings/fish-shell-release-4.gpg
          - /usr/share/keyrings/fish-shell-release-4.asc
      become: true
      args:
        creates: /usr/share/keyrings/fish-shell-release-4.gpg

    # Use deb822 sources OR the classic deb line. Deb822 is preferred on 24.04+
    - name: Add fish PPA (deb822 sources)
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/fish-shell-release-4.sources
        mode: "0644"
        content: |
          Types: deb
          URIs: https://ppa.launchpadcontent.net/fish-shell/release-4/ubuntu
          Suites: plucky
          Components: main
          Signed-By: /usr/share/keyrings/fish-shell-release-4.gpg
      become: true

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ setup_fish_packages }}"
        state: present
        update_cache: true
      become: true

    - name: Download fisher installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
        dest: /tmp/fisher.fish
        mode: '0755'
      become: true

    - name: Install fisher plugin manager
      ansible.builtin.shell: |
        source /tmp/fisher.fish
        fisher install jorgebucaran/fisher
      changed_when: true
      args:
        executable: /usr/bin/fish

    - name: Install fish plugins
      ansible.builtin.shell: fish -c "fisher install {{ item }}"
      loop: "{{ setup_fisher_plugins }}"
      changed_when: true
      args:
        executable: /usr/bin/fish

    - name: Configure tide
      ansible.builtin.shell: |
        tide configure --auto --style=Rainbow --prompt_colors='16 colors' --show_time='24-hour format' \
        --rainbow_prompt_separators=Vertical --powerline_prompt_heads=Sharp --powerline_prompt_tails=Flat \
        --powerline_prompt_style='One line' --prompt_spacing=Sparse --icons='Many icons' --transient=No
      changed_when: true
      args:
        executable: /usr/bin/fish
