---
# main tasks for setup

- name: Include standard packages
  ansible.builtin.include_tasks: packages.yml
  tags:
    - packages

- name: Include fish shell
  ansible.builtin.include_tasks: fish.yml
  tags:
    - fish_config
