---
# main tasks for setup

- name: Include standard packages
  ansible.builtin.include_tasks: packages.yml
  tags:
    - packages

- name: Include fish shell
  ansible.builtin.include_tasks: fish.yml
  tags:
    - fish_config

- name: Include docker
  ansible.builtin.include_tasks: docker.yml
  tags:
    - docker

- name: Include python
  ansible.builtin.include_tasks: python.yml
  tags:
    - python
