---
# main tasks for setup

- name: Include apt packages
  ansible.builtin.include_tasks: packages.yml

- name: Include fish shell
  ansible.builtin.include_tasks: fish.yml

- name: Include docker
  ansible.builtin.include_tasks: docker.yml

- name: Include k3d
  ansible.builtin.include_tasks: k3d.yml

- name: Include node
  ansible.builtin.include_tasks: node.yml

- name: Include lazy vim
  ansible.builtin.include_tasks: lazy.yml
