---
# main tasks for setup

- name: Include packages
  ansible.builtin.include_tasks: packages.yml
  tags:
    - packages

- name: Include fish shell configuration
  ansible.builtin.include_tasks: fish.yml
  tags:
    - fish_config
