---
# node tasks for setup

- name: Install Node
  tags:
    - node

  block:

    - name: Install latest Node.js
      become: false
      ansible.builtin.shell: |
        nvm install latest
        set --universal nvm_default_version latest
      changed_when: true
      args:
        executable: /usr/bin/fish

    - name: Install npm packages
      become: false
      community.general.npm:
        name: "{{ item }}"
        global: true
        state: latest
      loop: "{{ setup_npm_packages }}"
