---
# standard packages tasks for setup

- name: Install apt standard packages
  ansible.builtin.apt:
    name: "{{ setup_standard_packages }}"
    state: present
    update_cache: true
  tags:
    - packages
